version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      next-and-react:
        patterns:
          - next
          - react
          - react-dom
          - eslint-config-next
      sanity:
        patterns:
          - "@sanity/*"
  - package-ecosystem: npm
    directory: /studio
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      sanity-studio:
        patterns:
          - sanity
          - "@sanity/*"
          - react
          - react-dom
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
