/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  excerpt: string;
  body: SimplePortableText;
};

export type SimplePortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary?: string;
  capabilities?: Array<string>;
  icon?: "circle" | "leaves" | "bud" | "quatrefoil";
  order?: number;
  active?: boolean;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  about?: AboutSection;
  body?: SimplePortableText;
};

export type AboutSection = {
  _type: "aboutSection";
  eyebrow?: string;
  heading: string;
  intro?: string;
  people?: Array<
    {
      _key: string;
    } & TeamMember
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  contactName?: string;
  email?: string;
  phone?: string;
  address?: Address;
  hours?: Array<string>;
  primaryActionLabel?: string;
  primaryActionUrl?: string;
  url?: string;
  tagline?: string;
  areaServed?: Array<string>;
  sameAs?: Array<string>;
};

export type Address = {
  _type: "address";
  line1?: string;
  city?: string;
  region?: string;
  postalCode?: string;
  country?: string;
  note?: string;
};

export type PageHeader = {
  _type: "pageHeader";
  eyebrow?: string;
  heading: string;
  intro?: string;
};

export type TeamMember = {
  _type: "teamMember";
  role: string;
  name: string;
  href?: string;
  portrait?: ImageWithAlt;
  bio: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Post
  | SimplePortableText
  | Slug
  | Service
  | Page
  | AboutSection
  | SiteSettings
  | Address
  | PageHeader
  | TeamMember
  | SanityImageAssetReference
  | ImageWithAlt
  | SanityImageCrop
  | SanityImageHotspot
  | Cta
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/cms.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    name,    contactName,    email,    phone,    address,    hours,    primaryActionLabel,    primaryActionUrl,    url,    tagline,    areaServed,    sameAs  }
export type SiteSettingsQueryResult = {
  name: string;
  contactName: string | null;
  email: string | null;
  phone: string | null;
  address: Address | null;
  hours: Array<string> | null;
  primaryActionLabel: string | null;
  primaryActionUrl: string | null;
  url: string | null;
  tagline: string | null;
  areaServed: Array<string> | null;
  sameAs: Array<string> | null;
} | null;

// Source: src/lib/cms.ts
// Variable: homePageQuery
// Query: *[_type == "page" && slug.current == "home"][0]{    title,    description,    about{      eyebrow,      heading,      intro,      people[]{        _key,        role,        name,        href,        bio,        portrait{          asset->{            _id,            url,            metadata {              lqip,              dimensions { width, height }            }          },          alt,          hotspot,          crop        }      }    },    body  }
export type HomePageQueryResult = {
  title: string;
  description: string | null;
  about: {
    eyebrow: string | null;
    heading: string;
    intro: string | null;
    people: Array<{
      _key: string;
      role: string;
      name: string;
      href: string | null;
      bio: string;
      portrait: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
    }> | null;
  } | null;
  body: SimplePortableText | null;
} | null;

// Source: src/lib/cms.ts
// Variable: servicesQuery
// Query: *[_type == "service" && active != false] | order(order asc, title asc) {    _key,    title,    "slug": slug.current,    summary,    capabilities,    order  }
export type ServicesQueryResult = Array<{
  _key: null;
  title: string;
  slug: string;
  summary: string | null;
  capabilities: Array<string> | null;
  order: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    name,\n    contactName,\n    email,\n    phone,\n    address,\n    hours,\n    primaryActionLabel,\n    primaryActionUrl,\n    url,\n    tagline,\n    areaServed,\n    sameAs\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "page" && slug.current == "home"][0]{\n    title,\n    description,\n    about{\n      eyebrow,\n      heading,\n      intro,\n      people[]{\n        _key,\n        role,\n        name,\n        href,\n        bio,\n        portrait{\n          asset->{\n            _id,\n            url,\n            metadata {\n              lqip,\n              dimensions { width, height }\n            }\n          },\n          alt,\n          hotspot,\n          crop\n        }\n      }\n    },\n    body\n  }\n': HomePageQueryResult;
    '\n  *[_type == "service" && active != false] | order(order asc, title asc) {\n    _key,\n    title,\n    "slug": slug.current,\n    summary,\n    capabilities,\n    order\n  }\n': ServicesQueryResult;
  }
}
