declare const styles: {
  readonly contact: string;
  readonly contactCopy: string;
  readonly contactGrid: string;
  readonly contactHeading: string;
  readonly email: string;
  readonly ethosGrid: string;
  readonly ethosItem: string;
  readonly hero: string;
  readonly heroBody: string;
  readonly heroCta: string;
  readonly heroInner: string;
  readonly italic: string;
  readonly kicker: string;
  readonly main: string;
  readonly section: string;
  readonly sectionHeading: string;
  readonly sectionIntro: string;
  readonly shell: string;
  readonly teamGrid: string;
};
export = styles;
