declare const styles: {
  readonly actions: string;
  readonly contact: string;
  readonly contactCopy: string;
  readonly contactGrid: string;
  readonly contactHeading: string;
  readonly contactIntro: string;
  readonly formColumn: string;
  readonly hero: string;
  readonly heroBody: string;
  readonly heroContent: string;
  readonly heroGrid: string;
  readonly heroHeading: string;
  readonly homeBody: string;
  readonly principleBody: string;
  readonly principleItem: string;
  readonly principleTitle: string;
  readonly sectionGrid: string;
  readonly sectionIntro: string;
};
export = styles;
