declare const styles: {
  readonly activeLink: string;
  readonly activePrimaryDark: string;
  readonly desktopLink: string;
  readonly desktopNav: string;
  readonly inner: string;
  readonly item: string;
  readonly menuButton: string;
  readonly "mobile-menu-item-in": string;
  readonly "mobile-menu-item-out": string;
  readonly "mobile-menu-panel-in": string;
  readonly "mobile-menu-panel-out": string;
  readonly mobileContainer: string;
  readonly panel: string;
  readonly panelClosing: string;
  readonly panelOpen: string;
  readonly primaryItem: string;
  readonly primaryNav: string;
  readonly root: string;
  readonly solidOverlay: string;
  readonly wordmark: string;
};
export = styles;
